### ISSUE TITLE
Regexp with z-0

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-pulse#29]
See: https://github.com/taskcluster/taskcluster-pulse/blob/b150cfe56f2d1ae29a8fe3e7029195dba2227d25/src/api.js#L86

not sure what it's for... didn't read that far yet...
But `/^[A-Za-z-0-9_-]+$/` probably should be `/^[A-Za-z0-9_-]+$/`.

Notice the `z-0`, I'm not sure how it'll be interpreted, but when adding dash it's always best to add it at the end.

**Comment by Naillik1** [comment]
I don't think there's any difference in behaviour between the two, but the extra dash in 
`/^[A-Za-z-0-9_-]+$/` does make it harder to read and is a bit redundant. I'll get that.

**Comment by jonasfj** [comment]
yeah, I think you're right... It just seems scary :)

**Comment by urdaalex** [comment]
Apologies on my end, this was the result of a late night copy and past of the regex from the requirements page I was provided. This is indeed an extra dash which should be removed. Good catch!

**Comment by jonasfj** [comment]
Ps I filed a PR: https://github.com/taskcluster/taskcluster-pulse/pull/30

Feel free to hit merge whenever...

**Comment by jonasfj** [comment]
Fixed in #30
