### ISSUE TITLE
Escape other "names" in rabbitmq management lib

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#33]
Currently only `vhost` names are escaped (with `encodeURIComponent`). We probably also need to encode all the other names that will appear in the URI as well (e.g. users, queues).

First of all, some investigation is needed to see if rabbitmq actually supports user names like "a/b".

**Comment by itsbriany** [comment]
You can use `RabbitManager.encodeURIComponents` to return an object which encodes all the components specified. You can take a look at `RabbitManager.createQueue` as an example :)
