### ISSUE TITLE
Invalid schema http://schemas.taskcluster.net/pulse/v1/namespace-request.json

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-pulse#36]
These [lines](https://github.com/taskcluster/taskcluster-pulse/blob/1becbc2c5b4092cb9ff27e9b3902182c1715f5ba/schemas/namespace-request.yml#L12-L13) are invalid as no `id` property is specified, for these to be relative against.

**Comment by petemoore** [comment]
This could be solved by adding
```
    "id": "http://schemas.taskcluster.net/pulse/v1/namespace-request.json"
```
or by providing absolute urls for the `$ref` entries, I believe.

**Comment by petemoore** [comment]
This [validator](http://www.jsonschemavalidator.net/) is useful for troublshooting.

**Comment by petemoore** [comment]
See [section 7.2](http://json-schema.org/latest/json-schema-core.html#anchor27) of the json schema spec for details.

**Comment by petemoore** [comment]
Note, I believe in all our other schemas, we always provide absolute URLs for `$ref` entries, so that would be my preferred solution for consistency.

**Comment by imbstack** [comment]
@urdaalex any ideas about this?

**Comment by urdaalex** [comment]
@petemoore is correct. I looked at some examples and they do indeed reference absolute paths. I will make the necessary changes. Thanks for the insight Pete.

**Comment by petemoore** [comment]
No worries! Thanks for picking up so quickly. :-)
