### ISSUE TITLE
user not defined api.js

### ISSUE THREAD

**Issue by urdaalex** [taskcluster/taskcluster-pulse#38]
RabbitManager.createUser() does not return anything. This [line](https://github.com/taskcluster/taskcluster-pulse/blob/master/src/api.js#L129) results in user being set to undefined. 

Possible solution:
`await context.rabbit.createUser(newNamespace.username, newNamespace.password, ['taskcluster-pulse']);
user = newNamespace.username;`

**Comment by Hexcles** [comment]
Only the "getters" return values, and the method for creating and deleting
stuff generally return void in rabbitmq lib.

**Comment by urdaalex** [comment]
also now that I look at it, is it even possible to specify parameters by name in function calls [here](https://github.com/taskcluster/taskcluster-pulse/blob/master/src/api.js#L128-L134)? Excuse my limited JS knowledge

**Comment by imbstack** [comment]
So far as specifying by name is concerned, we use babel to compile the modern/future js we write into the current runnable stuff. So in tc-pulse, you can write


```js
    await context.rabbit.setUserPermissions({
      user: await context.rabbit.createUser(newNamespace.username, newNamespace.password, ['taskcluster-pulse']),
      vhost: '/',
      configurePattern: '',
      writePattern: `taskcluster/(exchanges|queues)/${newNamespace.namespace}/.*`,
      readPattern: 'taskcluster/exchanges/.*',
    }); 
} catch (err) {
...
```

but that would only work if setUserPermission is defined as follows:

```js
 async setUserPermissions({user, vhost, configurePattern, writePattern, readPattern}) {
```

which it isn't, it's missing the curly braces.

As it is written you need to pass in arguments in order.

**Comment by imbstack** [comment]
But yeah, the fix for this should be to split up the creation of the user and the setting of the permissions into two calls. Just `await` the results of `createUser` and then call `setUserPermissions` with `newNamespace.username`.

**Comment by Hexcles** [comment]
Is that the destructive assignment?

Speaking of which, Brian Yip and I briefly talked about the interface of
this API and thought that it was a bit messy and probably error-prone to
specify these "*patterns" in order. Is there a better convention/practice
when it comes to this kind of parameters in modern JS?

**Comment by imbstack** [comment]
@Hexcles: taskcluster uses that style of assignment (yep, [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)) often and I quite like it. It can even allow for setting defaults. I would support a move to that in the rabbitmanager api.

**Comment by itsbriany** [comment]
I'm guessing that if we use destructive assignment in `setUserPermissions`'s function signature, then we will also need to need to do the same for the rest of the `rabbitmanager` calls?

**Comment by Hexcles** [comment]
Probably just replace all the dict-like complex parameters with destructing
assignments? Like the "*patterns". If there is just name and/or vhost, we
could probably leave it as is. Not sure if this is not consistent though.
