### ISSUE TITLE
rabbit_tests result in a message queue leakage

### ISSUE THREAD

**Issue by itsbriany** [taskcluster/taskcluster-pulse#39]
Each time I successfully run the Rabbit Wrapper tests, I end up with two excess rabbitmq queues.
@Hexcles Any thoughts?

<img width="1265" alt="rabbitmq resource leakage" src="https://cloud.githubusercontent.com/assets/6740119/20026344/0add19e6-a2d8-11e6-9c58-cbb603bb7295.png">

**Comment by Hexcles** [comment]
Thank you Brian! It's indeed a bug. Actually, there's also leakage in users. Looking into the issue.
