### ISSUE TITLE
Make sure RabbitMQ permission regexs have start-of-line anchors

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#43]
According to [RabbitMQ document](https://www.rabbitmq.com/access-control.html), the permission patterns are just normal _regex_ and they do not need to match the whole string necessarily. We need to make sure we explicitly anchor them to the start of strings by using `^` in order to achieve the name scoping properly.

For example, a pattern `taskcluster/queue/test/.*` would give the user undesired permissions on things like `exchange/taskcluster/queue/test/.*` as well, which is outside our intended scope. Though unlikely, this could be a security flaw.

PulseGuardian has the `^` anchors: https://github.com/mozilla/pulseguardian/blob/d52886217ee63f911d199314949ac3aaf40c1870/pulseguardian/model/pulse_user.py#L74

The [Security Model](https://wiki.mozilla.org/Auto-tools/Projects/Pulse#Security_Model) section of Pulse spec actually uses both the start-of-line and end-of-line anchor (e.g. `^exchange/<username>/.*$`). AFAIK, the `$` is not necessary in this case.

**Comment by djmitche** [comment]
Thank you for noticing this!

**Comment by urdaalex** [comment]
I will tack this onto my current PR since I'm changing the permissions anyways.
