### ISSUE TITLE
API endpoint to get namespace information

### ISSUE THREAD

**Issue by itsbriany** [taskcluster/taskcluster-pulse#47]
Currently in https://github.com/taskcluster/taskcluster-pulse/blob/master/src/api.js, it looks like there is an endpoint which creates new namespaces. It would be nice to also have an endpoint which queries the namespace entities table to get a response with all information relevant to the queried namespace (contact info, username, password, etc...). Currently this is only done internally at https://github.com/taskcluster/taskcluster-pulse/blob/master/src/api.js#L139.

@urdaalex Any thoughts? :)

**Comment by Hexcles** [comment]
Something like `GET /namespace/:namespace` without input payload?

**Comment by itsbriany** [comment]
Yup.
