### ISSUE TITLE
Namespace validation

### ISSUE THREAD

**Issue by itsbriany** [taskcluster/taskcluster-pulse#49]
Currently, the TaskCluster-Pulse RabbitMonitor only monitors RabbitMQ queues with names starting with `taskcluster/`. 

In order to get the namespace info, we need to query the namespaces table. (For now, I am using each queue name as the namespace key). The problem is that namespaces only allow certain formats and in this case, the `/` in `taskcluster/` is not a valid character. Would it be sane to allow `/` as a valid namespace key character?

Alternatively, we could use a different format for selecting which queues to monitor such that only alphabetical characters are used (eg. monitor queues whose names start with `taskcluster` instead of `taskcluster/`).

For more details on how namespace info is queried: https://github.com/taskcluster/taskcluster-pulse/blob/alerter/src/api.js#L127-L129

**Comment by imbstack** [comment]
Why not just remove the "/"?

**Comment by itsbriany** [comment]
If we removed the "/", we could have queue names like `taskclusterfoo` or `taskclusterbar`. This readability is not optimal, but I guess for now it is viable?

**Comment by imbstack** [comment]
Oh, I see what you're saying.

Remove the entire "taskcluster/" and then everything after that is the namespace. Does that make sense?

**Comment by itsbriany** [comment]
Yeah :) Thanks for the clarification!
