### ISSUE TITLE
"exchanges" API endpoint not loaded in taskcluster-client

### ISSUE THREAD

**Issue by Naillik1** [taskcluster/taskcluster-pulse#51]
So, the exchanges endpoint ([https://github.com/taskcluster/taskcluster-pulse/blob/master/src/api.js#L50-L71](url)), unlike the other ones, isn't loading as a part of taskcluster-client ([https://github.com/taskcluster/taskcluster-client#methods-in-taskclusterpulse](url)) Not too sure about what's wrong or what needs to be done to make that happen, but the tools site UI needs that method to be completed. I might be missing something obvious, but I'm not sure. Anyone know why it's not there?

**Comment by Hexcles** [comment]
The built-in API references can be updated by a script. @imbstack might be
able to help doing a quick update as he has the write access on the client
repo. Or you can run the script (under taskcluster-client/bin/) yourself if
you are in a hurry (and send a PR).

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-client/pull/61
