### ISSUE TITLE
pulse.exchanges() should have a `continuationToken`

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-pulse#53]
Querystring parameters in tc-lib-api are always optional... I suggest taking `continuationToken`, `limit` and `namespace` as querystring options.

```js
let result = await pulse.exchanges({limit: ..., continuationToken: '...', namespace: '...'});
result === {exchanges: ['...', '...', ...], continuationToken: '...'}
```

Obviously, we wouldn't return a `continuationToken` if this is the last result... interpretation of the continuationToken is up to you, as far as API consumer is concerned it's an opaque string. Offset or name of next exchange might be useful...

Note: I'm not aware of what you are basing this one... But if it's significantly more efficient to list by exchange then maybe it should be: `v1/namespace/<namespace>/exchanges` and then namespace isn't an optional querystring parameter... That also feels more restful, but it's clearly not as powerful as being able to list everything, with optional filtering on namespace.

**Comment by djmitche** [comment]
The underlying API appears to not support continuation tokens, so i don't see a great benefit here -- we would just end up querying rabbitmq multiple times, each time throwing away most of the result.

**Comment by jonasfj** [comment]
@djmitche I haven't tried this but are you sure it's not supported?
https://github.com/rabbitmq/rabbitmq-management/pull/76

I don't know if it's production yet... it doesn't look like it supported on 3.5.7 which pulse.m.o is running..
But perhaps we want to add a `continuationToken`, we can just leave it unused for now..

**Comment by djmitche** [comment]
It's not in [the documentation](https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/www/api/index.html)

I suspect the concern is changing this endpoint later by adding continuation tokens.  If that's the case, I'd rather just remove it for now, since it provides very little value.

**Comment by jonasfj** [comment]
Yeah, it's not in the docs before it's not released yet, or at-least not in the version we use...

 But yes, my concern is that I don't want to break API... hence, if we just add it now and never use it that's fine...
