### ISSUE TITLE
Q: Do we need all the (required) fields in email-request and irc-request?

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#55]
When creating a new namespace, the API asks for contact info in the request, which has a lot of fields nested in a couple of layers. I probably missed some discussions on this, but I'm just wondering if all the fields are necessary. For example, I understand that we need an IRC handle (username/channel) or an email address to contact (either manually or by automatic alerts), but do we also need to specify (and, mandatorily) message, subject, content, etc.? I imagine these would be generated automatically based on the alerts.

And for the reference, here's what the constructor parameters of `PulseListener` (part of tc-client) would look like if we require all these fields (I could flatten out the `payload` layer to make it slightly less cumbersome):

```
/**
 * Create new PulseListener
 *
 * options: { 
 *   ...
 *   credentials: {
 *     namespace:         // Namespace to prefix queues/exchanges (optional)
 *                        // defaults to `username` if given otherwise ""
 *     hostname:          // Hostname to connect to using username/password
 *                        // defaults to pulse.mozilla.org
 *     connectionString:  // connectionString overwrites username/password and
 *                        // hostname (if given)
 *     contact: {
 *       // Contact info sent to taskcluster-pulse when requesting credentials
 *       method:          // 'irc' or 'email'
 *       payload: {
 *         // Specify these fields if IRC is used (require channel or user, not both)
 *         channel:
 *         user:
 *         message:       // required
 *         // Specify these fields if email is used
 *         address:       // required
 *         subject:       // required
 *         content:       // required
 *       }
 *     }
 *     username:          // Pulse username (deprecated)
 *     password:          // Pulse password (deprecated)
 *   }
 *   ...
 * }
 */
```

Thanks!

**Comment by djmitche** [comment]
This is the jsdoc for the PulseListener constructor, right?  It might make the most sense for the `contact` field to follow the same structure as the [`namespace` endpoint](https://docs.taskcluster.net/reference/core/taskcluster-pulse/references/api#namespace).  Which is to say, something like

```
 *     // Contact info sent to taskcluster-pulse when requesting credentials
 *     contact: { \\ one of:
 *       method: 'irc',
 *       payload: {
 *         // specify one of channel or user
 *         channel:
 *         user:
 *         message:       // required
 *       }
 *     }, { // or:
 *       method: 'email',
 *       payload: {
 *         address:       // required
 *         subject:       // required
 *         content:       // required
 *       }
 *     }
```

It does seem that the message/subject/content are not required.

**Comment by itsbriany** [comment]
To my knowledge, the contact information fields are required because the TaskCluster-Pulse RabbitAlerter queries the Azure tables to read contact information for a given namespace such that it can generate an appropriate alert.

**Comment by Hexcles** [comment]
@djmitche Yes that's the doc for PulseListener (it already has a doc block and I'm just updating it). Thanks for the suggestion!

@itsbriany I understand why we need contact information, but my confusion is if all the fields are useful and even mandatory. Like in the `RabbitMonitor` scenario, the messages are generated based on what's going wrong (https://github.com/taskcluster/taskcluster-pulse/blob/alerter/src/rabbitalerter.js#L146). Fields like `subject`, `content`, `message` supplied to our API when creating a namespace don't seem to be used, al least so far.

I'm concerned about these required fields need to be supplied everywhere we instantiate a `PulseListener`, which is quite a few places across the whole taskcluster, so we don't want to introduce unnecessary mandatory fields.

**Comment by urdaalex** [comment]
@Hexcles I'm curious as to the outcome as this as well. I'm running into a similar situation when updating pulse-go. The schemas were copied from [tc-notify](https://github.com/taskcluster/taskcluster-notify/tree/master/schemas) but I can see why it may not be feasible for tc-pulse to have required `subject`, `content`, etc. I personally think we can scrap those attributes.

**Comment by Hexcles** [comment]
Thanks @urdaalex for the context!

In this case, I'm proposing #58 to completely remove those fields for now (see the PR for more rationales), which will simplify the client usage of `taskcluster-pulse` quite a bit -- in fact, that is all the users of `PulseListener`. Please feel free to comment if you have any suggestion or opposition.

**Comment by Hexcles** [comment]
@urdaalex FYI #58 has been merged, so your go client integration can base on the simplified request schema now.

Also closing this issue.
