### ISSUE TITLE
Need to add "pulse.taskcluster.net" as a SAN of the SSL cert

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#60]
Currently `pulse.taskcluster.net` is not in the SAN list of the certificate. Thus browsers and nodejs refuse to connect to it.

**Comment by djmitche** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1320210

**Comment by Hexcles** [comment]
Fixed
