### ISSUE TITLE
Cleanup after API tests

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#64]
Similar to #22, `api_test.js` also has some leakage, namely that the users created during `createNamespace` are not removed after tests.

We can fix the issue in a similar way as what we did for #22, i.e. remove all the users added during tests in teardown, but I think the ideal solution is to use mock (sinon) to stub out the `createOrUpdateUser` method of `rabbit` object in Pulse API's context, so that we avoid creating users altogether and in the meantime assert the method is properly called.

However, it is not as easy as I thought. It seems we do not hold a direct reference to (the context of) the API handlers, which makes it hard to stub out the `rabbit` object. In tests, `helper.pulse` is just the client (generated by taskcluster-client); `webServer` (instantiated in `helper.js`, but not exposed at the moment) does not provide easy ways to manipulate the internals of API handlers either, AFAIK.

**Comment by djmitche** [comment]
I believe this is solved now.
