### ISSUE TITLE
Implement monitoring v1

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-pulse#81]
From our discussion last week, I think this means:
 * monitoring queue lengths and sending warnings at one size and deleting at another, larger size
   * where there is no contact info, there's no warning to send
 * deleting queues and exchanges with no matching namespace
 * terminating connections for users not associated with a namespace
 * terminating connections which have existed for several times longer than the rotation interval

All of this within the scope of the configured namespace prefix (so we're not clobbering things belonging to pulseguardian!)

We discussed finding some better thresholding algorithms, but I think we can defer that to a subsequent PR (maybe still before final deployment though).

**Comment by imbstack** [comment]
It occurs to me now that when you get one of these nastygrams from pulseguardian, it is actionable. Namely, you can go to the pulseguardian site itself and delete your queue. Should we make it so that you can do this to tc-pulse queues as well if you have the proper scopes? As it stands all you can do is leave it.

**Comment by djmitche** [comment]
I suspect the more common action is to restart the service consuming from the queue, or making your transient queues autodelete?

Anyway, sounds like a future feature, if it does prove useful -- it wouldn't be hard.

**Comment by djmitche** [comment]
Let's see how this works in day-to-day usage and re-visit.

**Comment by djmitche** [comment]
(I think most of this is implemented -- it's just not clear how well)
